name: Add Song

on:
  push:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  update_main:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Add Song
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }} 
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }} 
        SPOTIFY_TOKEN: ${{ secrets.SPOTIFY_TOKEN }} 
        SPOTIFY_REFRESH: ${{ secrets.SPOTIFY_REFRESH }} 
      run: |
        npm i
        npm start
    