name: Scrape Songs

on:
  workflow_dispatch:
  push:
  # schedule:
  #   - cron: '*/5 * * * *'
  

jobs:
  scrape_songs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Scrape Songs
      run: |
        npm i
        npm start

    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Go to branch "main"
      run: git checkout main
  
    - name: Commit changes
      run: |
        git add .
        git commit -m "Update songs branch"
    
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: main
        github_token: ${{ secrets.TOKEN }}
        force: true
    

    